### ISSUE TITLE
Image does not fucntion correctly when using IPv6 addresses

### ISSUE THREAD

**Issue by cyberjacob** [haproxytech/vmware-haproxy#1]
When provisioned with IPv6 addresses, the created VM boots but gets stuck when configuring the network interfaces. This eventually fails and the VM finishes to boot, however it does not have any settings applied. For example the network interfaces do not have any IP addresses applied, and logging in with the specified root password does not work.

For testing, I used the following settings:

`loadbalance.dataplane_port`: `5556`
`appliance.permit_root_login`: `True`
`network.hostname`:  `tanzuproxy.example.com`
`network.frontend_ip`:  `2001:xxx:xxx:105::6/64`
`loadbalance.haproxy_user`: `admin`
`network.nameservers`:  `2001:xxx:xxx:102::5,2001:xxx:xxx:102::18`
`appliance.root_pwd`:  `*******`
`loadbalance.service_ip_range`:  `2001:xxx:xxx:110::/64`
`loadbalance.haproxy_pwd`: `*******`
`network.management_ip`:  `2001:xxx:xxx:102::13/64`
`network.workload_ip`:  `2001:xxx:xxx:109::2/64`
`network.workload_gateway`:  `2001:xxx:xxx:109::1`
`network.frontend_gateway`:  `2001:xxx:xxx:105::1`
`network.management_gateway`:  `2001:xxx:xxx:102::1`

**Comment by brakthehack** [comment]
Hi @cyberjacob. Thanks for the report. IPv6 is not yet supported on VMware w/ Tanzu. If you try to enable a VMware with Tanzu workload, you should hit an error message. But, I can see how that might not be clear given that HAProxy is a pre-requisite for that setup.

It's definitely a goal to support IPv6 going forward, so I'd like to leave this bug open, but even if we address the issue here with the appliance, it won't work out of the box until a future vSphere patch, so please use IPv4 for now.

I will push a change to mention the limited support for IPv6 in the README. Thanks for bringing it to our attention.

**Comment by cyberjacob** [comment]
Hi Brian, that's for confirming that. It's a pity there's nothing more obvious (or at all, as I didn't find anything) in the VMWare documentation noting the latest version of the standard isn't supported.
